# These are supported funding model platforms

github: ['Leluka11']
patreon: ['Leluka11']
open_collective: ['Leluka11']
ko_fi: ['Leluka11']
tidelift: ['Leluka11']
community_bridge: ['Leluka11']
liberapay: ['Leluka11']
issuehunt: ['Leluka11']
otechie: ['Leluka11']
lfx_crowdfunding: ['Leluka11']
custom: ['https://github.com/Leluka11/Valorant-Checker/']
